config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root 'homes#top'
  get 'homes/about' => 'homes#about'
  
  resources :items
  resources :cart_items
  resources :addresses
  resources :users do
    get '/unsubscribe' => 'customers#unsubscribe'
    patch '/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
  end

  
  namespace :admin do
    get 'admin/homes/top' => 'admin/homes#top'
    resources :items
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  # バリデーション設定
  validates :name, presence: true
  validates :body, {presence: true, length: { maximum: 200}}
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :user
  
  validates :item_id, :amount, presence: true
  validates :amount, numericality:{ only_integer: true }
  
  def sum_of_price
    item.with_tax_price * amount
  end 
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  
  attachment :image
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/list.rb
class List < ApplicationRecord
    attachment :image
    
    validates :title,presence: true
    validates :body, presence: true
    validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def full_name
    self.last_name + "" + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + "" + self.first_name_kana
  end 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end
  
  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    def index
      @books = Book.all
      @user = current_user
      @book = Book.new
    end
    
    def show
      @book = Book.find(params[:id])
      # @book.user_id = current_user.id
      @books = Book.new
      @user = @book.user
    end
    
    def create
      @book = Book.new(book_params)
      # @book.user_id = current_user.id
      @user = current_user
      if @book.save
        flash[:notice] = 'You have created book successfully.'
        redirect_to book_path(@book.id)
      else
        @books = Book.all
        render 'index'
      end
    end
    
    def edit
      @book = Book.find(params[:id])
    end
    
    def update
      @book = Book.find(params[:id])
      @book.update
      redirect_to books_path
    end
    
    
    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
    end
    
    private
    def book_params
      params.require(:book).permit(:name, :body, :user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
    
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to public_user_path(@user.id)
    else
      render 'edit'
    end
  end
  
  def withdraw
    @user = User.find(params[:user_id])
    if @user.update(is_active: false)
      reset_session
    end
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。" 
    redirect_to root_path
  end
  
    # 退会の仕方について
  def unsubscribe
    @user = current_user.id
  end
  
  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code,
                                     :address, :telephone_number, :is_active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="conteiner">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <h2 class="mb-3"><%= @user.full_name %>さんの会員情報編集</h2>
      <%= form_with model: [:admin, @user], local:true do |f| %>
      <div class="form-group row">
        <label for="custmer-id" class="col-sm-3 col-form-label">会員ID</label>
        <div clsdd="col-9">
          <%= @user.id %>
        </div>
      </div>
      <div class="form-group row">
        <label for="customer-name" class="col-sm-3 col-form-label">氏名</label>
        <div clsdd="col-9">
          <%= f.text_field :last_name %>
          <%= f.text_field :first_name %>
        </div>
      </div>
      <div class="form-group row">
        <label for="customer-kana" class="col-sm-3 col-form-label">フリガナ</label>
        <div clsdd="col-9">
          <%= f.text_field :last_name_kana %>
          <%= f.text_field :first_name_kana %>
        </div>
      </div>
      <div class="form-group row">
        <label for="csutomer-postal_code" class="col-sm-3 col-form-label">郵便番号</label>
        <div clsdd="col-9">
          <%= f.text_field :postal_code %>
        </div>
      </div>
      <div class="form-group row">
        <label for="customer-address" class="col-sm-3 col-form-label">住所</label>
        <div clsdd="col-9">
          <%= f.text_field :address %>
        </div>
      </div>
      <div class="form-group row">
        <label for="customer-telephone_number" class="col-sm-3 col-form-label">電話番号</label>
        <div clsdd="col-9">
          <%= f.text_field :telephone_number %>
        </div>
      </div>
      <div class="form-group row">
        <label for="customer-email" class="col-sm-3 col-form-label">メールアドレス</label>
        <div clsdd="col-9">
          <%= f.text_field :email %>
        </div>
      </div>
      <div class="form-group row">
        <label for="customer-status" class="col-sm-3 col-form-label">会員ステータス</label>
        <div clsdd="col-9">
          <%= f.radio_button :is_active, true, checked: "checked" %>
          <%= f.label :is_active, "有効" %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, "退会" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
        <%= link_to '注文履歴一覧を見る', admin_items_path, class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="conteiner">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <table class="table">
        <theard>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </theard>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.is_active %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="conteiner">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <table class="table table-boderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <!--名字と名前を合体させたメソッドを作成-->
            <td>氏名</td>
            <td><%= @user.full_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @user.full_name_kana %></td>
          </tr>
          <tr>
            <td>郵便梅郷</td>
            <td><%= @user.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @user.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @user.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><%= @user.is_active %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/user/edit.html.erb
<div class="container">
  <div class="row">
    <h2 class="pt-3 pb-3">会員情報編集</h2>
    <div class="col-sm-12">
    <%= form_with model: [:public, @customer], local:true do |f| %>
      <div class="form-group row">
        <label for="name" class="col-sm-3 col-form-label">氏名</label>
        <div class="col-sm-9">
          <%= f.text_field :last_name %>
          <%= f.text_field :first_name %>
        </div>
      </div>
      <div class="form-group row">
        <label for="namekana" class="col-sm-3 col-form-label">カナ</label>
        <div class="col-sm-9">
          <%= f.text_field :last_name_kana %>
          <%= f.text_field :first_name_kana %>
        </div>
      </div>
      <div class="form-group row">
        <label for="postal_code" class="col-sm-3 col-form-label">郵便番号</label>
        <div class="col-sm-9">
          <%=f.text_field :postal_code %>
        </div>
      </div>
      <div class="form-group row">
        <label for="address" class="col-sm-3 col-form-label">住所</label>
        <div class="col-sm-9">
          <%= f.text_field :address %>
        </div>
      </div>
      <div class="form-group row">
        <label for="telephone_number" class="col-sm-3 col-form-label">電話番号</label>
        <div class="col-sm-9">
          <%= f.text_field :telephone_number %>
        </div>
      </div>
      <div class="form-group row">
        <label for="email" class="col-sm-3 col-form-label">メールアドレス</label>
        <div class="col-sm-9">
          <%= f.text_field :email %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 mx-auto">
          <button type="submit" class="btn btn-success">編集内容を保存</button>
          <%= link_to '退会する', public_customer_unsubscribe_path(@customer.id), class: 'btn btn-danger' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <h1>マイページ</h1>
      <div class="top-text">
        <p class="col-3">基本情報</p>
        <%= link_to "編集する", edit_user_path(@user), class: "col-3 btn btn-success ml-3" %>
      </div>
      <table class="table">
        <tbody>
          <tr>
            <td>氏名</td>
            <td><%= @user.full_name %></td>
          </tr>
          <tr>
            <td>カナ</td>
            <td><%= @user.full_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @user.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @user.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @user.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td<%= @user.email %>></td>
          </tr>
        </tbody>
      </table>
      <P>配送先</P><%= link_to "一覧を見る", addresses_path, class: "btn btn-primary mt-5 ml-3" %>
      <P>注文履歴</P><%= link_to "一覧を見る", orders_path, class: "btn btn-primary mt-5 ml-3" %>
    </div>
  </div>
</div>

app/views/user/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h1 class="text-center">本当に退会しますか？</h1>
        <p class="text-center">退会すると、会員登録情報や<br>
        これまでの購入履歴が閲覧できなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。</p>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center">
    <%= link_to '退会しない', user_path(@user), class: "btn btn-primary" %>
    <%= link_to '退会する', user_withdraw_user_path(@user), method: :patch,　data: { confirm: '本当に退会しますか?'}, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render "devise/shared/sideber", user: @user, books: @book %>
    <div class="col-8 mt-5">
      <h1>Users</h1>
      <% @users.each do |user| %>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag @user, :user_image, fallback: "no_image.jpg" %>
                <%= link_to @user.name, user_path(@user) %>
              </td>
              <td><%= user.introduction %></td>
              <td><%= link_to "show", user_path(user.id) %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <%= render "devise/shared/sideber", user: @user, books: @books %>
    <div class="col-8">
      <h1>Book</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>Option</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @user, :user_image, fallback: "no_image.jpg" %>
              <%= @user.name %>
            </td>
            <td><%= link_to @book.name, book_path(@book) %></td>
            <td><%= @book.body %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>