config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root 'homes#top'
  get 'homes/about' => 'homes#about'
  
  resources :items
  resources :cart_items
  resources :addresses
  resources :users do
    get '/unsubscribe' => 'customers#unsubscribe'
    patch '/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
  end

  
  namespace :admin do
    get 'admin/homes/top' => 'admin/homes#top'
    resources :items
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  # バリデーション設定
  validates :name, presence: true
  validates :body, {presence: true, length: { maximum: 200}}
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :user
  
  validates :item_id, :amount, presence: true
  validates :amount, numericality:{ only_integer: true }
  
  def sum_of_price
    item.with_tax_price * amount
  end 
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  
  attachment :image
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/list.rb
class List < ApplicationRecord
    attachment :image
    
    validates :title,presence: true
    validates :body, presence: true
    validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def full_name
    self.last_name + "" + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + "" + self.first_name_kana
  end 
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagono</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body class="d-flex flex-column vh-100">
    <header class="shadow">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3 border rounded" href="/">ながのCAKE</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to '商品一覧', items_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item ">
                <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <%= link_to 'カート', cart_items_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-light border rounded' %>
              </li>
              <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to '商品一覧', admin_items_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <%= link_to '会員一覧', admin_users_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <= link_to '注文履歴一覧', admin_root_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-light border rounded' %>
              </li>
              <% else %>
              <li class="nav-item">
               <%= link_to 'About', '/homes/about', class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <%= link_to '商品一覧', items_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <%= link_to '新規登録', new_user_registration_path, class: 'nav-link text-light border rounded' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: 'nav-link text-light border rounded' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>